### ISSUE TITLE
TODO 0.1.0

### ISSUE THREAD

**Issue by Rastopyr** [Rastopyr/chrome-yarb#2]
## Specification
Demands

- [ ] Specify demands of Reader
- [ ] Choose data storage for parsed file
- [ ] Create enviroment for nw.js

## Data structure
Specify data structure for Reader

- [ ] Models
- [ ] Adapters
- [ ] Serializers
