### ISSUE TITLE
TODO 0.2.0

### ISSUE THREAD

**Issue by Rastopyr** [Rastopyr/chrome-yarb#3]
### Epub

- [ ] Unzip epub
- [ ] Read xhtml/xml/css from epub container
- [ ] Transform data, to owner data
- [ ] Save book in some data stroage
